### ISSUE TITLE
why some paper with a bold title

### ISSUE THREAD

**Issue by kanbaiou** [zssloth/Embedded-Neural-Network#6]
thank you for your contribution 

I notice that some papers have a bold title 
for example: 

**Learning Compression from Limited Unlabeled Data**
**AMC: AutoML for Model Compression and Acceleration on Mobile Devices**

I just want to confirm do you  mean these one should be paid attention to....?

Actually I have tried some algorithm in this area， and think AMC is a milestone.

**Comment by zssloth** [comment]
Hi, these bold papers are those quite impress me after reading. Personally, they indeed should be paid attention to as you said.

**Comment by kanbaiou** [comment]
thank you very much
谢谢！
